# Generated by Django 5.1.5 on 2026-09-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0017_dimemployee_archive_note_dimemployee_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_fa', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('board', 'هیئت\u200cمدیره'), ('executive', 'مدیریت عامل'), ('staff', 'واحد ستادی'), ('department', 'واحد'), ('section', 'زیرواحد')], default='section', max_length=12)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('sales_channel', models.CharField(blank=True, choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B'), ('psp', 'فروش PSP')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='hr.orgunit')),
            ],
            options={
                'verbose_name': 'واحد سازمانی',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_fa', models.CharField(max_length=150)),
                ('is_head', models.BooleanField(default=False)),
                ('on_sales_sheet', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='sales.dimemployee')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hr.orgunit')),
            ],
            options={
                'verbose_name': 'سمت',
                'ordering': ('-is_head', 'sort_order', 'id'),
            },
        ),
    ]
