# Generated by Django 5.1.5 on 2026-07-20 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_factkpi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimCostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=120)),
                ('is_direct', models.BooleanField(default=False, help_text='Direct manufacturing cost vs overhead.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'dim cost categories',
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='DimMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('cutting', 'Cutting / slitting line (برش)'), ('print', 'Printing unit (چاپ)')], default='cutting', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='DimProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=100)),
                ('unit', models.CharField(default='roll', max_length=30)),
                ('piece_rate_rial', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('index_factor', models.DecimalField(decimal_places=2, default=1, help_text='شاخص — weight used to convert output into index units.', max_digits=8)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ProductionBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ideal_output_per_shift', models.PositiveIntegerField(default=16000, help_text='مجموع!H3 — desired output per machine per shift.')),
                ('monthly_shift_capacity', models.PositiveIntegerField(default=120, help_text='مجموع!H4 — total shifts available in the month.')),
                ('hours_per_shift', models.PositiveSmallIntegerField(default=8, help_text='مجموع!H5')),
                ('full_system_staff', models.PositiveIntegerField(default=33, help_text='مجموع!H6 — staff needed to run the full system.')),
                ('total_headcount', models.PositiveIntegerField(default=675, help_text='ورودی!K2 — total man-days excluding Fridays.')),
                ('ideal_shift_count', models.PositiveIntegerField(default=155, help_text='KPI!E3 uses 155 shifts for the ideal case.')),
                ('days_in_month', models.PositiveSmallIntegerField(default=30)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_benchmark', to='core.dimperiod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactMaterialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.CharField(choices=[('cutting', 'Cutting (برش)'), ('print', 'Printing (چاپ)')], max_length=10)),
                ('input_weight', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('output_weight', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_balance', to='core.dimperiod')),
            ],
            options={
                'unique_together': {('period', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='FactPrintColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_count', models.PositiveSmallIntegerField()),
                ('area_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_colors', to='core.dimperiod')),
            ],
            options={
                'ordering': ('period', 'color_count'),
                'unique_together': {('period', 'color_count')},
            },
        ),
        migrations.CreateModel(
            name='FactProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_shifts', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('output_units', models.DecimalField(decimal_places=2, default=0, help_text='Rolls for cutting lines, m² for the print unit.', max_digits=18)),
                ('waste_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('repair_count', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('downtime_breakdown_shifts', models.DecimalField(decimal_places=2, default=0, help_text='خواب به خاطر خرابی', max_digits=8)),
                ('downtime_sizechange_shifts', models.DecimalField(decimal_places=2, default=0, help_text='خواب به خاطر تغییر سایز', max_digits=8)),
                ('downtime_nowork_shifts', models.DecimalField(decimal_places=2, default=0, help_text='خواب به خاطر عدم کار', max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production', to='production.dimmachine')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production', to='core.dimperiod')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('period', 'machine__sort_order'),
                'unique_together': {('period', 'machine')},
            },
        ),
        migrations.CreateModel(
            name='FactProductionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.dimcostcategory')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_costs', to='core.dimperiod')),
            ],
            options={
                'unique_together': {('period', 'category')},
            },
        ),
        migrations.CreateModel(
            name='FactProductionRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('piece_rate_rial', models.DecimalField(decimal_places=0, default=0, help_text='Snapshot of the rate used for this period.', max_digits=18)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_revenue', to='core.dimperiod')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.dimproduct')),
            ],
            options={
                'unique_together': {('period', 'product')},
            },
        ),
    ]
