# Generated by Django 5.1.5 on 2026-08-04 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_sitesetting_sales_grain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'material category (دسته کالا)',
                'verbose_name_plural': 'material categories',
                'ordering': ('sort_order', 'name_fa'),
            },
        ),
        migrations.CreateModel(
            name='QuoteReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('win', 'دلیل انتخاب'), ('lose', 'دلیل عدم انتخاب')], max_length=4)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'quote reason (دلیل انتخاب/رد)',
                'ordering': ('kind', 'sort_order', 'name_fa'),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=150)),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('ton', 'تن'), ('pcs', 'عدد'), ('roll', 'رول'), ('m', 'متر'), ('lit', 'لیتر'), ('pack', 'بسته'), ('ctn', 'کارتن')], default='pcs', max_length=6)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='commercial.materialcategory')),
            ],
            options={
                'verbose_name': 'material (کالای مصرفی)',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_no', models.CharField(blank=True, max_length=24, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('requester_unit', models.CharField(blank=True, max_length=120)),
                ('requested_on', models.DateField()),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'ثبت\u200cشده'), ('quoting', 'در حال استعلام'), ('awarded', 'تامین\u200cکننده انتخاب شد'), ('ordered', 'سفارش ثبت شد'), ('cancelled', 'لغو شده')], default='open', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='commercial.material')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='core.dimperiod')),
            ],
            options={
                'verbose_name': 'purchase request (درخواست خرید)',
                'ordering': ('-requested_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('activity', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supplier (تامین\u200cکننده)',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price_rial', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('quoted_on', models.DateField(blank=True, null=True)),
                ('delivery_days', models.PositiveSmallIntegerField(default=0, help_text='زمان تحویل به روز')),
                ('validity_days', models.PositiveSmallIntegerField(default=0, help_text='اعتبار قیمت به روز')),
                ('is_selected', models.BooleanField(default=False)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='commercial.purchaserequest')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='commercial.quotereason')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='commercial.supplier')),
            ],
            options={
                'verbose_name': 'quote (استعلام قیمت)',
                'ordering': ('unit_price_rial', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_no', models.CharField(blank=True, max_length=24, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_price_rial', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('ordered_on', models.DateField()),
                ('delivered_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('buying', 'در حال خرید'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شد'), ('cancelled', 'لغو شد')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commercial.material')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.dimperiod')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='commercial.purchaserequest')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='commercial.quote')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commercial.supplier')),
            ],
            options={
                'verbose_name': 'purchase order (سفارش خرید)',
                'ordering': ('-ordered_on', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status'], name='commercial__status_938402_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['requested_on'], name='commercial__request_608e10_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['is_selected'], name='commercial__is_sele_7d9277_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('request', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='commercial__status_9592b9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['ordered_on'], name='commercial__ordered_832951_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['material', 'ordered_on'], name='commercial__materia_e948dd_idx'),
        ),
    ]
