# Generated by Django 5.1.5 on 2026-08-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8)),
                ('jalali_year', models.PositiveSmallIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'document counter (شمارنده اسناد)',
                'unique_together': {('prefix', 'jalali_year')},
            },
        ),
    ]
