# Generated by Django 5.1.5 on 2026-08-05 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_documentcounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'bank (بانک عامل)',
                'ordering': ('sort_order', 'name_fa'),
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='origin',
            field=models.CharField(choices=[('domestic', 'داخلی'), ('foreign', 'خارجی')], default='domestic', max_length=8),
        ),
        migrations.CreateModel(
            name='ForeignOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_no', models.CharField(blank=True, max_length=24, unique=True)),
                ('pi_no', models.CharField(db_index=True, max_length=60)),
                ('registration_no', models.CharField(blank=True, db_index=True, max_length=30)),
                ('statistical_no', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('goods_desc', models.CharField(blank=True, max_length=200)),
                ('weight_ton', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'دلار'), ('EUR', 'یورو'), ('AED', 'درهم'), ('CNY', 'یوان')], default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='ارزش ارزی پرونده', max_digits=18)),
                ('registered_on', models.DateField(blank=True, help_text='تاریخ ثبت سفارش', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='تاریخ اعتبار ثبت سفارش', null=True)),
                ('queued_on', models.DateField(blank=True, help_text='تاریخ ورود به صف تخصیص ارز', null=True)),
                ('allocated_on', models.DateField(blank=True, help_text='تاریخ تایید تخصیص ارز', null=True)),
                ('purchase_deadline', models.DateField(blank=True, help_text='مهلت خرید ارز', null=True)),
                ('expected_queue_days', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('registered', 'ثبت سفارش'), ('queued', 'در صف تخصیص ارز'), ('allocated', 'تخصیص ارز'), ('remitted', 'حواله ارز'), ('purchased', 'خرید انجام شد'), ('shipping', 'در حال حمل'), ('customs', 'گمرک'), ('cleared', 'ترخیص شد'), ('closed', 'بسته شده'), ('cancelled', 'لغو شده')], default='draft', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commercial.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign_orders', to='commercial.material')),
                ('owner', models.ForeignKey(blank=True, help_text='مسئول پرونده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreign_orders', to='commercial.supplier')),
            ],
            options={
                'verbose_name': 'foreign order (پرونده واردات)',
                'ordering': ('-registered_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('USD', 'دلار'), ('EUR', 'یورو'), ('AED', 'درهم'), ('CNY', 'یوان')], max_length=3)),
                ('kind', models.CharField(choices=[('free', 'آزاد'), ('centre', 'مرکز مبادله'), ('customs', 'گمرکی')], max_length=8)),
                ('on_date', models.DateField()),
                ('rate_rial', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('is_manual', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'fx rate (نرخ ارز)',
                'ordering': ('-on_date', 'currency', 'kind'),
                'indexes': [models.Index(fields=['currency', 'kind', '-on_date'], name='commercial__currenc_a2891d_idx')],
                'unique_together': {('currency', 'kind', 'on_date')},
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('at', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('blocked_reason', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='commercial.foreignorder')),
            ],
            options={
                'verbose_name': 'order event (اقدام پرونده)',
                'ordering': ('-at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_no', models.CharField(blank=True, max_length=20)),
                ('bl_no', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='شماره بارنامه')),
                ('container_no', models.CharField(blank=True, db_index=True, max_length=40)),
                ('carrier', models.CharField(blank=True, max_length=120, verbose_name='شرکت حمل')),
                ('origin_port', models.CharField(blank=True, max_length=120)),
                ('destination_port', models.CharField(blank=True, max_length=120)),
                ('goods_desc', models.CharField(blank=True, max_length=200)),
                ('weight_ton', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('value_amount', models.DecimalField(decimal_places=2, default=0, help_text='ارزش این محموله به ارز پرونده', max_digits=18)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('arrived_on', models.DateField(blank=True, help_text='رسیدن بار به بندر', null=True)),
                ('released_on', models.DateField(blank=True, help_text='تاریخ آزادسازی بار', null=True)),
                ('declared_on', models.DateField(blank=True, help_text='تاریخ اظهار گمرکی', null=True)),
                ('cleared_on', models.DateField(blank=True, help_text='تاریخ ترخیص', null=True)),
                ('free_days', models.PositiveSmallIntegerField(default=0, help_text='روزهای رایگان نگهداری کانتینر')),
                ('demurrage_daily_rial', models.DecimalField(decimal_places=0, default=0, help_text='دموراژ روزانه پس از پایان Free Days', max_digits=18)),
                ('storage_daily_rial', models.DecimalField(decimal_places=0, default=0, help_text='انبارداری روزانه', max_digits=18)),
                ('status', models.CharField(choices=[('ready', 'آماده بارگیری'), ('departed', 'حرکت کرده'), ('at_sea', 'روی دریا'), ('at_port', 'بندر مقصد'), ('customs', 'گمرک'), ('cleared', 'ترخیص شد'), ('delivered', 'تحویل کارخانه'), ('cancelled', 'لغو شده')], default='ready', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='commercial.foreignorder')),
            ],
            options={
                'verbose_name': 'shipment (محموله)',
                'ordering': ('-eta', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ShipmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('goods', 'بهای کالا'), ('freight', 'کرایه حمل'), ('insurance', 'بیمه'), ('duty', 'حقوق و عوارض گمرکی'), ('clearance', 'ترخیصیه و سپرده'), ('transit', 'حمل داخلی و ترانزیت'), ('demurrage', 'دموراژ / حق توقف'), ('storage', 'انبارداری'), ('other', 'سایر')], max_length=10)),
                ('amount_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('amount_fx', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'دلار'), ('EUR', 'یورو'), ('AED', 'درهم'), ('CNY', 'یوان')], max_length=3)),
                ('is_estimate', models.BooleanField(default=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='commercial.shipment')),
            ],
            options={
                'verbose_name': 'shipment cost (هزینه محموله)',
                'ordering': ('shipment', 'kind'),
            },
        ),
        migrations.AddIndex(
            model_name='foreignorder',
            index=models.Index(fields=['status'], name='commercial__status_595ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='foreignorder',
            index=models.Index(fields=['registered_on'], name='commercial__registe_393ced_idx'),
        ),
        migrations.AddIndex(
            model_name='foreignorder',
            index=models.Index(fields=['bank', 'status'], name='commercial__bank_id_5b342b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', '-at'], name='commercial__order_i_755d18_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='commercial__status_5961b3_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['eta'], name='commercial__eta_068fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['arrived_on'], name='commercial__arrived_71a697_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentcost',
            index=models.Index(fields=['shipment', 'kind'], name='commercial__shipmen_6fb825_idx'),
        ),
    ]
