# Generated by Django 5.1.5 on 2026-08-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_seed_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignorder',
            name='arrived_on',
            field=models.DateField(blank=True, help_text='رسیدن بار به بندر', null=True),
        ),
        migrations.AddField(
            model_name='foreignorder',
            name='customs_declared_on',
            field=models.DateField(blank=True, help_text='تاریخ اظهار گمرکی', null=True),
        ),
        migrations.AddField(
            model_name='foreignorder',
            name='customs_value_rial',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ اظهار گمرکی', max_digits=22),
        ),
        migrations.AddField(
            model_name='foreignorder',
            name='factory_entry_on',
            field=models.DateField(blank=True, help_text='ورود کالا به کارخانه', null=True),
        ),
        migrations.AddField(
            model_name='foreignorder',
            name='inspection',
            field=models.CharField(choices=[('Q', 'در انتظار'), ('R', 'انجام شده')], default='Q', max_length=1, verbose_name='بازرسی'),
        ),
        migrations.AddField(
            model_name='foreignorder',
            name='insurance',
            field=models.CharField(choices=[('Q', 'در انتظار'), ('R', 'انجام شده')], default='Q', max_length=1, verbose_name='بیمه'),
        ),
        migrations.AddField(
            model_name='foreignorder',
            name='last_status_note',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='foreignorder',
            name='production_cert_on',
            field=models.DateField(blank=True, help_text='تاریخ گواهی تولید', null=True),
        ),
        migrations.AddField(
            model_name='foreignorder',
            name='proforma_expires_on',
            field=models.DateField(blank=True, help_text='تاریخ انقضای پروفرما', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='due_on',
            field=models.DateField(blank=True, help_text='سررسید پرداخت به فروشنده', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='سود دیرکرد اعلامی فروشنده', max_digits=18),
        ),
        migrations.AddField(
            model_name='shipment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='foreignorder',
            name='expected_queue_days',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='foreignorder',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('permit', 'منتظر مجوز صنعت و معدن'), ('registered', 'ثبت سفارش شده'), ('queued', 'در صف تخصیص ارز'), ('allocated', 'تخصیص ارز'), ('remitted', 'حواله ارز'), ('purchased', 'خرید انجام شد'), ('shipping', 'در حال حمل'), ('customs', 'گمرک'), ('cleared', 'ترخیص شد'), ('closed', 'بسته شده'), ('cancelled', 'لغو شده')], default='draft', max_length=12),
        ),
    ]
