# Generated by Django 5.1.5 on 2026-08-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_foreignorder_arrived_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignorder',
            name='cleared_on',
            field=models.DateField(blank=True, help_text='تاریخ ترخیص', null=True),
        ),
    ]
