# Generated by Django 5.1.5 on 2026-08-12 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0007_foreignorder_cleared_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=120)),
                ('advance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days', models.PositiveSmallIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'payment term (شرایط پرداخت)',
                'ordering': ('sort_order', 'name_fa'),
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'نقدی'), ('cheque', 'چک'), ('transfer', 'حواله بانکی'), ('lc', 'اعتبار اسنادی داخلی'), ('other', 'سایر')], max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_note',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'نقدی'), ('cheque', 'چک'), ('transfer', 'حواله بانکی'), ('lc', 'اعتبار اسنادی داخلی'), ('other', 'سایر')], max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_note',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='quotereason',
            name='kind',
            field=models.CharField(choices=[('win', 'دلیل انتخاب'), ('lose', 'دلیل عدم انتخاب'), ('sample', 'دلیل رد نمونه')], max_length=8),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='commercial.paymentterm'),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='commercial.paymentterm'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_no', models.CharField(blank=True, max_length=24, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('spec', models.CharField(blank=True, max_length=300)),
                ('requested_on', models.DateField()),
                ('received_on', models.DateField(blank=True, null=True)),
                ('decided_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'درخواست شد'), ('received', 'دریافت شد'), ('testing', 'در حال آزمایش'), ('approved', 'تایید شد'), ('rejected', 'رد شد')], default='requested', max_length=10)),
                ('lab_note', models.TextField(blank=True, verbose_name='نتیجه آزمایش')),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, help_text='تاییدکننده / ردکننده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='commercial.material')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='commercial.quote')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='commercial.quotereason')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='commercial.purchaserequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='commercial.supplier')),
            ],
            options={
                'verbose_name': 'sample (نمونه)',
                'ordering': ('-requested_on', '-id'),
                'indexes': [models.Index(fields=['status'], name='commercial__status_f74c9d_idx'), models.Index(fields=['supplier', 'material'], name='commercial__supplie_ced630_idx'), models.Index(fields=['requested_on'], name='commercial__request_a6ab1f_idx')],
            },
        ),
    ]
