# Generated by Django 5.1.5 on 2026-09-15 18:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_seed_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='فاکتور رسمی'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='درصد ارزش افزوده', max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='فاکتور رسمی'),
        ),
        migrations.AddField(
            model_name='quote',
            name='vat_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='درصد ارزش افزوده', max_digits=5),
        ),
    ]
