# Generated by Django 5.1.5 on 2026-09-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0010_official_invoice_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='code',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='code',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quotereason',
            name='code',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
