# Generated by Django 5.1.5 on 2026-07-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('domain', models.CharField(default='sales', max_length=30)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('direction', models.CharField(choices=[('higher', 'Higher is better'), ('lower', 'Lower is better')], default='higher', max_length=10)),
                ('formula_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('domain', 'code'),
            },
        ),
        migrations.CreateModel(
            name='DimPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jalali_year', models.PositiveSmallIntegerField()),
                ('jalali_month', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'period (Jalali month)',
                'ordering': ('jalali_year', 'jalali_month'),
                'unique_together': {('jalali_year', 'jalali_month')},
            },
        ),
    ]
