# Generated by Django 5.1.5 on 2026-07-20 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('company', 'Company'), ('team', 'Team'), ('employee', 'Employee'), ('machine', 'Machine / production line'), ('product', 'Product')], max_length=12)),
                ('scope_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scope_label', models.CharField(blank=True, max_length=150)),
                ('actual', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('target', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('ideal', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('deviation', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('efficiency_pct', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.dimkpi')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='core.dimperiod')),
            ],
            options={
                'ordering': ('period', 'kpi', 'scope'),
                'unique_together': {('period', 'kpi', 'scope', 'scope_id')},
            },
        ),
    ]
