# Generated by Django 5.1.5 on 2026-07-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_factkpi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factkpi',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='factkpi',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='factkpi',
            unique_together={('period', 'kpi', 'scope', 'scope_id', 'channel')},
        ),
    ]
