# Generated by Django 5.1.5 on 2026-07-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_notification_kpiformula'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('chart_theme', models.CharField(choices=[('modern', 'مدرن'), ('corporate', 'سازمانی'), ('vivid', 'پرکنتراست'), ('mono', 'تک\u200cرنگ مینیمال')], default='modern', max_length=20)),
                ('company_name', models.CharField(default='شرکت کاغذ حساس نمابر مهر', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
