# Generated by Django 5.1.5 on 2026-07-25 17:54

import django.db.models.deletion
from django.db import migrations, models


def backfill_months(apps, schema_editor):
    """
    Give the existing rows their kind, Gregorian bounds and code.

    They stay leaves (no week children), so every historical fact keeps
    pointing at a valid leaf period and nothing needs re-entering.
    """
    from apps.core import jalali

    DimPeriod = apps.get_model("core", "DimPeriod")
    for p in DimPeriod.objects.all():
        p.kind = "month"
        p.seq = p.jalali_month
        p.start_date = jalali.to_gregorian(p.jalali_year, p.jalali_month, 1)
        p.end_date = jalali.to_gregorian(
            p.jalali_year,
            p.jalali_month,
            jalali.month_days(p.jalali_year, p.jalali_month),
        )
        p.code = f"{p.jalali_year}.{p.jalali_month:02d}"
        p.save(update_fields=["kind", "seq", "start_date", "end_date", "code"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimperiod',
            options={'ordering': ('jalali_year', 'jalali_month', 'seq'), 'verbose_name': 'period (month / week / day)'},
        ),
        migrations.AlterUniqueTogether(
            name='dimperiod',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dimperiod',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='dimperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimperiod',
            name='kind',
            field=models.CharField(choices=[('month', 'ماه'), ('week', 'هفته'), ('day', 'روز')], default='month', max_length=8),
        ),
        migrations.AddField(
            model_name='dimperiod',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.dimperiod'),
        ),
        migrations.AddField(
            model_name='dimperiod',
            name='seq',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dimperiod',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        # Backfill before the constraints land, so the unique month index is
        # applied to rows that already have kind='month' set correctly.
        migrations.RunPython(backfill_months, noop),
        migrations.AddConstraint(
            model_name='dimperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'month')), fields=('jalali_year', 'jalali_month'), name='uniq_month_period'),
        ),
        migrations.AddConstraint(
            model_name='dimperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('parent', None), _negated=True), fields=('parent', 'seq'), name='uniq_child_seq'),
        ),
    ]
