# Generated by Django 5.1.5 on 2026-07-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_dimperiod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='min_week_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sales_grain',
            field=models.CharField(choices=[('month', 'ماهانه'), ('week', 'هفتگی')], default='month', help_text='دانه\u200cبندی ثبت اطلاعات فروش', max_length=8),
        ),
    ]
