# Generated by Django 5.1.5 on 2026-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesetting_min_week_days_sitesetting_sales_grain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='sales_grain',
            field=models.CharField(choices=[('month', 'ماهانه'), ('week', 'هفتگی'), ('day', 'روزانه')], default='month', help_text='دانه\u200cبندی ثبت اطلاعات فروش', max_length=8),
        ),
    ]
