# Generated by Django 5.2.17 on 2026-09-27 09:53

import django.db.models.deletion
from django.db import migrations, models


SALES = {"sales_team": ["team"], "sales_org": ["organizational"], "sales_b2b": ["b2b"]}


def backfill(apps, schema_editor):
    """
    Write down, for every existing month and section, the grain it is already
    recorded at — so nothing on the site moves on the day this ships.

    * A section with figures in the month keeps the level they sit on.
    * A sales section without figures keeps the month's current calendar
      depth (a month the CEO already made weekly stays weekly for sales).
    * تولید without figures stays monthly: its sheet has only ever written to
      the month, whatever the calendar under it.
    * مالی without figures gets no row: it starts at its default (روزانه) the
      first time it is opened, which also deepens the calendar to days.
    """
    DimPeriod = apps.get_model("core", "DimPeriod")
    PeriodGrain = apps.get_model("core", "PeriodGrain")
    GrainDefault = apps.get_model("core", "GrainDefault")
    SiteSetting = apps.get_model("core", "SiteSetting")
    FactSalesMonthly = apps.get_model("sales", "FactSalesMonthly")
    FactSalesProvince = apps.get_model("sales", "FactSalesProvince")
    FactSalesByCustomerGroup = apps.get_model("sales", "FactSalesByCustomerGroup")
    FactProduction = apps.get_model("production", "FactProduction")
    FactProductionCost = apps.get_model("production", "FactProductionCost")
    FactProductionRevenue = apps.get_model("production", "FactProductionRevenue")
    FactPrintColor = apps.get_model("production", "FactPrintColor")
    CashMovement = apps.get_model("finance", "CashMovement")

    setting = SiteSetting.objects.filter(singleton=True).first()
    sales_default = setting.sales_grain if setting else "month"
    for dept in SALES:
        GrainDefault.objects.get_or_create(department=dept, defaults={"grain": sales_default})
    GrainDefault.objects.get_or_create(department="production", defaults={"grain": "month"})
    GrainDefault.objects.get_or_create(department="finance", defaults={"grain": "day"})

    def held(ids, dept):
        if dept == "production":
            models = (FactProduction, FactProductionCost, FactProductionRevenue, FactPrintColor)
            return any(m.objects.filter(period_id__in=ids).exists() for m in models)
        if dept == "finance":
            return CashMovement.objects.filter(period_id__in=ids).exists()
        return any(
            m.objects.filter(period_id__in=ids, channel__in=SALES[dept]).exists()
            for m in (FactSalesMonthly, FactSalesProvince, FactSalesByCustomerGroup)
        )

    for month in DimPeriod.objects.filter(kind="month"):
        weeks = list(DimPeriod.objects.filter(parent=month))
        days = list(DimPeriod.objects.filter(parent__in=weeks))
        depth = "day" if days else "week" if weeks else "month"
        levels = [
            ("day", [d.id for d in days]),
            ("week", [w.id for w in weeks]),
            ("month", [month.id]),
        ]
        for dept in (*SALES, "production", "finance"):
            grain = next((g for g, ids in levels if ids and held(ids, dept)), None)
            if grain is None:
                if dept == "finance":
                    continue
                grain = "month" if dept == "production" else depth
            PeriodGrain.objects.get_or_create(
                month=month, department=dept, defaults={"grain": grain},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesetting_sales_grain'),
        ('sales', '0018_dimemployee_is_placeholder_no_marketer'),
        ('production', '0002_alter_factproduction_status'),
        ('finance', '0012_drop_budget_sales_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrainDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('sales_team', 'فروش همکار'), ('sales_org', 'فروش بانکی'), ('sales_b2b', 'فروش B2B'), ('production', 'تولید'), ('finance', 'مالی (نقدینگی)')], max_length=20, unique=True)),
                ('grain', models.CharField(choices=[('month', 'ماهانه'), ('week', 'هفتگی'), ('day', 'روزانه')], default='month', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodGrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('sales_team', 'فروش همکار'), ('sales_org', 'فروش بانکی'), ('sales_b2b', 'فروش B2B'), ('production', 'تولید'), ('finance', 'مالی (نقدینگی)')], max_length=20)),
                ('grain', models.CharField(choices=[('month', 'ماهانه'), ('week', 'هفتگی'), ('day', 'روزانه')], default='month', max_length=8)),
                ('month', models.ForeignKey(limit_choices_to={'kind': 'month'}, on_delete=django.db.models.deletion.CASCADE, related_name='grains', to='core.dimperiod')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('month', 'department'), name='uniq_month_grain')],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
