# Generated by Django 5.1.5 on 2026-08-13 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalali_year', models.PositiveSmallIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'letter counter (شمارنده نامه)',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=24, unique=True)),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع')),
                ('body', models.TextField(blank=True, verbose_name='متن')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده')], default='draft', max_length=6)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='office.letter')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'letter (نامه)',
                'ordering': ('-sent_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LetterAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('mime', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='office.letter')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'letter attachment (پیوست نامه)',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='LetterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_fa', models.CharField(max_length=60, unique=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'letter tag (برچسب نامه)',
                'ordering': ('name_fa',),
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='letters', to='office.lettertag'),
        ),
        migrations.CreateModel(
            name='LetterAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('paraph', 'پاراف'), ('refer', 'ارجاع'), ('note', 'یادداشت'), ('archive', 'بایگانی')], max_length=8)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letter_actions', to=settings.AUTH_USER_MODEL)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='office.letter')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'letter action (اقدام نامه)',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['letter', 'created_at'], name='office_lett_letter__02c2f4_idx'), models.Index(fields=['actor', 'kind'], name='office_lett_actor_i_b3ac2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LetterRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('to', 'گیرنده'), ('cc', 'رونوشت')], default='to', max_length=2)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='office.letter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'letter recipient (گیرنده نامه)',
                'ordering': ('kind', 'id'),
                'indexes': [models.Index(fields=['user', 'archived_at'], name='office_lett_user_id_df10d5_idx'), models.Index(fields=['user', 'read_at'], name='office_lett_user_id_d667a7_idx')],
                'unique_together': {('letter', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['status', '-sent_at'], name='office_lett_status_30bde8_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['sender', 'status'], name='office_lett_sender__7169c4_idx'),
        ),
    ]
