# Generated by Django 5.1.5 on 2026-08-13 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_fa', models.CharField(max_length=60, unique=True)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name': 'task tag (برچسب کار)',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='نام پروژه')),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('status', models.CharField(choices=[('active', 'در جریان'), ('done', 'تمام شده'), ('archived', 'بایگانی')], default='active', max_length=8)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project (پروژه)',
                'ordering': ('status', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('manager', 'مدیر پروژه'), ('member', 'عضو')], default='member', max_length=8)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='office.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project member (عضو پروژه)',
                'ordering': ('role', 'id'),
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', through='office.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('description', models.TextField(blank=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد'), ('urgent', 'فوری')], default='normal', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='office.project')),
            ],
            options={
                'verbose_name': 'task (وظیفه)',
                'ordering': ('done_at', 'due_on', '-priority', 'order', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='office.task')),
            ],
            options={
                'verbose_name': 'task comment (یادداشت وظیفه)',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='office.project')),
            ],
            options={
                'verbose_name': 'task group (دسته\u200cبندی کار)',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='office.taskgroup'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='office.tasktag'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='office_proj_status_9b89d6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'done_at'], name='office_task_assigne_183fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['creator', 'done_at'], name='office_task_creator_dacd56_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'done_at'], name='office_task_project_1d2d47_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_on'], name='office_task_due_on_212937_idx'),
        ),
    ]
