# Generated by Django 5.1.5 on 2026-08-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_tasktag_project_projectmember_project_members_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letteraction',
            name='visibility',
            field=models.CharField(choices=[('all', 'همه\u200cی گیرندگان'), ('private', 'خصوصی')], default='all', max_length=7),
        ),
        migrations.AddField(
            model_name='letterrecipient',
            name='sees_history',
            field=models.BooleanField(default=True),
        ),
    ]
