# Generated by Django 5.1.5 on 2026-08-03 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_sitesetting_sales_grain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('in', 'فقط واریز'), ('out', 'فقط برداشت'), ('both', 'هر دو')], default='both', max_length=5)),
                ('expects_credit_line', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'cash category (دسته نقدینگی)',
                'verbose_name_plural': 'cash categories',
                'ordering': ('sort_order', 'name_fa'),
            },
        ),
        migrations.CreateModel(
            name='FinanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('opening_balance_rial', models.DecimalField(decimal_places=0, default=0, help_text='موجودی نقد در ابتدای اولین روزِ ثبت\u200cشده', max_digits=20)),
                ('opening_on', models.DateField(blank=True, help_text='تاریخی که موجودی بالا به آن تعلق دارد', null=True)),
                ('low_balance_rial', models.DecimalField(decimal_places=0, default=0, help_text='آستانه هشدار کمبود نقدینگی — صفر یعنی بدون هشدار', max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('facility', 'تسهیلات دریافتی'), ('lending', 'قرض پرداختی'), ('partner', 'جاری شرکا')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('counterparty', models.CharField(help_text='بانک، شرکت یا شخص طرف حساب', max_length=150)),
                ('principal_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('rate_pct', models.DecimalField(decimal_places=2, default=0, help_text='نرخ سود سالانه (٪) — برای قرض\u200cالحسنه صفر', max_digits=6)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('installments', models.PositiveSmallIntegerField(default=0, help_text='تعداد اقساط — صفر یعنی بدون زمان\u200cبندی')),
                ('status', models.CharField(choices=[('active', 'جاری'), ('settled', 'تسویه\u200cشده'), ('overdue', 'معوق'), ('cancelled', 'لغوشده')], default='active', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credit line (تسهیلات / قرض / جاری)',
                'ordering': ('kind', 'counterparty', 'title'),
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'واریز'), ('out', 'برداشت')], max_length=3)),
                ('amount_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Returned for revision')], default='draft', max_length=16)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.cashcategory')),
                ('period', models.ForeignKey(help_text='روزِ گزارش (برگ روز از درخت دوره\u200cها)', on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='core.dimperiod')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credit_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.creditline')),
            ],
            options={
                'ordering': ('period', 'direction', 'category__sort_order'),
                'indexes': [models.Index(fields=['period', 'direction'], name='finance_cas_period__35a5d3_idx'), models.Index(fields=['status'], name='finance_cas_status_298320_idx')],
                'unique_together': {('period', 'direction', 'category', 'credit_line')},
            },
        ),
    ]
