# Generated by Django 5.1.5 on 2026-08-03 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesetting_sales_grain'),
        ('finance', '0002_seed_cash_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_no', models.CharField(blank=True, max_length=40)),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='شبا')),
                ('kind', models.CharField(choices=[('bank', 'حساب بانکی'), ('cash', 'صندوق'), ('petty', 'تنخواه')], default='bank', max_length=6)),
                ('opening_balance_rial', models.DecimalField(decimal_places=0, default=0, help_text='موجودی این حساب پیش از اولین روزِ ثبت\u200cشده', max_digits=20)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'bank account (حساب)',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.AddField(
            model_name='financesetting',
            name='unit',
            field=models.CharField(choices=[('rial', 'ریال'), ('toman', 'تومان')], default='rial', help_text='واحد نمایش؛ ذخیره\u200cسازی همیشه ریال است', max_length=6),
        ),
        migrations.AlterField(
            model_name='financesetting',
            name='opening_balance_rial',
            field=models.DecimalField(decimal_places=0, default=0, help_text='منسوخ — موجودی اولیه اکنون روی هر حساب ثبت می\u200cشود', max_digits=20),
        ),
        migrations.AlterUniqueTogether(
            name='cashmovement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.bankaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='cashmovement',
            unique_together={('period', 'direction', 'category', 'credit_line', 'account')},
        ),
    ]
