# Generated by Django 5.1.5 on 2026-09-13 22:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesetting_sales_grain'),
        ('finance', '0004_move_opening_balance_to_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='دستهٔ والد — اگر خالی باشد، این دسته در سطح اول است', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.cashcategory'),
        ),
        migrations.AddField(
            model_name='financesetting',
            name='variance_threshold_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='انحراف از چند درصد به بالا مهم شمرده شود', max_digits=5),
        ),
        migrations.AddField(
            model_name='financesetting',
            name='variance_threshold_rial',
            field=models.DecimalField(decimal_places=0, default=0, help_text='انحراف از چه مبلغی به بالا مهم شمرده شود — صفر یعنی بدون کف مبلغی', max_digits=20),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('jalali_year', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('end_period', models.ForeignKey(help_text='آخرین ماه بودجه', on_delete=django.db.models.deletion.PROTECT, related_name='budgets_ending', to='core.dimperiod')),
                ('start_period', models.ForeignKey(help_text='اولین ماه بودجه', on_delete=django.db.models.deletion.PROTECT, related_name='budgets_starting', to='core.dimperiod')),
            ],
            options={
                'verbose_name': 'budget (بودجه)',
                'verbose_name_plural': 'budgets',
                'ordering': ('-jalali_year', 'title'),
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'واریز'), ('out', 'برداشت')], max_length=3)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.budget')),
                ('category', models.ForeignKey(help_text='دستهٔ نقدینگی — باید برگ باشد، چون حرکت\u200cها فقط روی برگ ثبت می\u200cشوند', on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.cashcategory')),
                ('credit_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.creditline')),
            ],
            options={
                'verbose_name': 'budget line (قلم بودجه)',
                'verbose_name_plural': 'budget lines',
                'ordering': ('sort_order', 'category__sort_order'),
            },
        ),
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'مصوب'), ('closed', 'بسته\u200cشده')], default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='finance.budget')),
                ('period', models.ForeignKey(help_text='ماه — بودجه هرگز روی هفته ذخیره نمی\u200cشود', on_delete=django.db.models.deletion.PROTECT, related_name='budget_periods', to='core.dimperiod')),
            ],
            options={
                'verbose_name': 'budget month (ماه بودجه)',
                'verbose_name_plural': 'budget months',
                'ordering': ('period__jalali_year', 'period__jalali_month'),
            },
        ),
        migrations.CreateModel(
            name='BudgetAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('baseline_rial', models.DecimalField(blank=True, decimal_places=0, help_text='مبلغ در لحظهٔ تصویب — پس از آن تغییر نمی\u200cکند', max_digits=20, null=True)),
                ('variance_note', models.TextField(blank=True, help_text='علت انحراف — برای انحراف\u200cهای مهم')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='finance.budgetline')),
                ('budget_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='finance.budgetperiod')),
            ],
            options={
                'verbose_name': 'budget amount (مبلغ بودجه)',
                'verbose_name_plural': 'budget amounts',
                'ordering': ('line__sort_order',),
            },
        ),
        migrations.CreateModel(
            name='BudgetAmountChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('new_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('after_approval', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='finance.budgetamount')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'budget change (تغییر بودجه)',
                'verbose_name_plural': 'budget changes',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['amount', '-created_at'], name='finance_bud_amount__94f1de_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget', 'direction'], name='finance_bud_budget__2abd51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('budget', 'category', 'credit_line', 'direction')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetperiod',
            unique_together={('budget', 'period')},
        ),
        migrations.AddIndex(
            model_name='budgetamount',
            index=models.Index(fields=['budget_period', 'line'], name='finance_bud_budget__cc12b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetamount',
            unique_together={('budget_period', 'line')},
        ),
    ]
