# Generated by Django 5.1.5 on 2026-09-15 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesetting_sales_grain'),
        ('finance', '0008_default_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetline',
            options={'ordering': ('sort_order', 'category__sort_order'), 'verbose_name': 'budget line (سرفصل بودجه)', 'verbose_name_plural': 'budget lines'},
        ),
        migrations.CreateModel(
            name='BudgetActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals', to='finance.budgetline')),
                ('period', models.ForeignKey(help_text='هفته، یا ماهی که به هفته تقسیم نشده', on_delete=django.db.models.deletion.PROTECT, related_name='budget_actuals', to='core.dimperiod')),
            ],
            options={
                'verbose_name': 'budget actual (رقم واقعی سرفصل)',
                'verbose_name_plural': 'budget actuals',
                'ordering': ('period__start_date', 'line__sort_order'),
                'indexes': [models.Index(fields=['period', 'line'], name='finance_bud_period__b49765_idx')],
                'unique_together': {('line', 'period')},
            },
        ),
    ]
