# Generated by Django 5.1.5 on 2026-09-17 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesetting_sales_grain'),
        ('finance', '0010_budget_actuals_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetactual',
            name='period',
            field=models.ForeignKey(help_text='ماه — ارقام واقعی بودجه ماهانه ثبت می\u200cشوند', on_delete=django.db.models.deletion.PROTECT, related_name='budget_actuals', to='core.dimperiod'),
        ),
    ]
