# Generated by Django 5.1.5 on 2026-09-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_budget_actual_monthly_help'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetSalesForecast',
        ),
    ]
