# Generated by Django 5.1.5 on 2026-07-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('', '— (no data-entry section)'), ('production', 'تولید'), ('sales_org', 'فروش سازمانی'), ('sales_team', 'تیم فروش (همکار)')], default='', max_length=20),
        ),
    ]
