# Generated by Django 5.1.5 on 2026-07-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_color_user_job_title_fa_user_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('', '— (no data-entry section)'), ('production', 'تولید'), ('sales_org', 'فروش بانکی'), ('sales_team', 'فروش همکار'), ('sales_b2b', 'فروش B2B')], default='', max_length=20),
        ),
    ]
