# Generated by Django 5.1.5 on 2026-08-04 19:43

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seyfi_factory_manager_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='ورود دو مرحله\u200cای'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_hex, max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('login', 'ورود دو مرحله\u200cای'), ('enable', 'فعال\u200cسازی ورود دو مرحله\u200cای')], default='login', max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sends', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'purpose', 'consumed_at'], name='accounts_ot_user_id_3ddaa8_idx')],
            },
        ),
    ]
