# Generated by Django 5.1.5 on 2026-07-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seyfi_factory_manager_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_access',
            field=models.BooleanField(default=False, verbose_name='admin panel access (explicit grant)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator (system management)'), ('executive', 'Executive (CEO / board)'), ('manager', 'Manager / supervisor (approves data)'), ('operator', 'Operator (enters data)'), ('viewer', 'Viewer (read-only dashboards)')], default='viewer', max_length=20),
        ),
    ]
