# Generated by Django 5.1.5 on 2026-08-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_admin_access_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('', '— (no data-entry section)'), ('production', 'تولید'), ('sales_org', 'فروش بانکی'), ('sales_team', 'فروش همکار'), ('sales_b2b', 'فروش B2B'), ('finance', 'مالی')], default='', max_length=20),
        ),
    ]
