# Generated by Django 5.1.5 on 2026-08-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_two_factor_enabled_user_two_factor_enabled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(choices=[('login', 'ورود دو مرحله\u200cای'), ('enable', 'فعال\u200cسازی ورود دو مرحله\u200cای'), ('otp_login', 'ورود با کد پیامکی'), ('reset', 'بازیابی رمز عبور')], default='login', max_length=12),
        ),
    ]
