# Generated by Django 5.1.5 on 2026-08-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_otpchallenge_purpose'),
        ('accounts', '0008_alter_user_department'),
    ]

    operations = [
    ]
