# Generated by Django 5.1.5 on 2026-08-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_department'),
        ('accounts', '0009_merge_20260805_0920'),
    ]

    operations = [
    ]
