# Generated by Django 5.1.5 on 2026-08-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('', '— (no data-entry section)'), ('production', 'تولید'), ('sales_org', 'فروش بانکی'), ('sales_team', 'فروش همکار'), ('sales_b2b', 'فروش B2B'), ('finance', 'مالی'), ('commercial', 'بازرگانی داخلی'), ('commercial_foreign', 'بازرگانی خارجی')], default='', max_length=20),
        ),
    ]
