# Generated by Django 5.1.15 on 2026-09-30 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فاز')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name': 'phase (فاز تیمیار)',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=120, verbose_name='مسئول')),
                ('start_on', models.DateField(verbose_name='شروع')),
                ('end_on', models.DateField(verbose_name='پایان / ددلاین')),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('todo', 'شروع نشده'), ('doing', 'در حال انجام'), ('blocked', 'متوقف'), ('done', 'انجام شده')], default='todo', max_length=8)),
                ('is_milestone', models.BooleanField(default=False)),
                ('done_on', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teamyar.task')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='teamyar.phase')),
            ],
            options={
                'verbose_name': 'task (فعالیت تیمیار)',
                'ordering': ('order', 'start_on', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='موضوع')),
                ('kind', models.CharField(choices=[('vendor', 'با تیمیار'), ('internal', 'داخلی'), ('training', 'آموزش'), ('steering', 'کمیته راهبری')], default='vendor', max_length=10)),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی شده'), ('held', 'برگزار شد'), ('cancelled', 'لغو شد')], default='planned', max_length=10)),
                ('held_at', models.DateTimeField(verbose_name='زمان')),
                ('duration_min', models.PositiveSmallIntegerField(default=60)),
                ('attendees', models.TextField(blank=True, verbose_name='حاضرین')),
                ('agenda', models.TextField(blank=True, verbose_name='دستور جلسه')),
                ('summary', models.TextField(blank=True, verbose_name='خلاصه')),
                ('decisions', models.TextField(blank=True, verbose_name='مصوبات')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='teamyar.task')),
            ],
            options={
                'verbose_name': 'meeting (جلسه تیمیار)',
                'ordering': ('-held_at',),
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('happened_at', models.DateTimeField(verbose_name='زمان')),
                ('kind', models.CharField(choices=[('call', 'تماس تلفنی'), ('message', 'پیام / چت'), ('email', 'ایمیل / نامه'), ('visit', 'حضوری'), ('issue', 'مشکل'), ('decision', 'تصمیم'), ('note', 'یادداشت'), ('system', 'تغییر وضعیت')], default='note', max_length=10)),
                ('counterpart', models.CharField(blank=True, max_length=150, verbose_name='طرف گفتگو')),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع')),
                ('body', models.TextField(blank=True, verbose_name='شرح')),
                ('resolved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='teamyar.meeting')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='teamyar.task')),
            ],
            options={
                'verbose_name': 'log entry (رویداد تیمیار)',
                'ordering': ('-happened_at', '-id'),
                'indexes': [models.Index(fields=['happened_at'], name='teamyar_log_happene_229356_idx')],
            },
        ),
    ]
