# Generated by Django 5.1.5 on 2026-10-01 20:55

import django.db.models.deletion
from django.db import migrations, models


def seed_and_file(apps, schema_editor):
    """
    The charter's twelve modules, then everything typed before modules
    existed filed under the module its title names.
    """
    from apps.core import jalali
    from apps.teamyar.modules import CHARTER, YEAR, guess

    Module = apps.get_model("teamyar", "Module")
    Task = apps.get_model("teamyar", "Task")
    Meeting = apps.get_model("teamyar", "Meeting")
    if not Module.objects.exists():
        for i, c in enumerate(CHARTER):
            Module.objects.create(
                title=c.title, owner=c.owner, specialist=c.specialist,
                keywords="، ".join(c.keywords), order=i,
                starts_on=jalali.to_gregorian(YEAR, c.workshop, 1),
                ends_on=jalali.to_gregorian(YEAR, 12, jalali.month_days(YEAR, 12)),
            )
    mods = list(Module.objects.all())
    for t in Task.objects.select_related("phase"):
        m = guess(mods, t.title, t.phase.title if t.phase else "")
        if m:
            Task.objects.filter(pk=t.pk).update(module=m)
    for mt in Meeting.objects.all():
        m = guess(mods, mt.title)
        key = m.pk if m else None
        if key is None and mt.task_id:
            key = Task.objects.filter(pk=mt.task_id).values_list("module_id", flat=True).first()
        if key:
            Meeting.objects.filter(pk=mt.pk).update(module_id=key)


class Migration(migrations.Migration):

    dependencies = [
        ('teamyar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='نام ماژول')),
                ('owner', models.CharField(blank=True, max_length=150, verbose_name='مسئول داخلی')),
                ('specialist', models.CharField(blank=True, max_length=150, verbose_name='متخصص تیمیار')),
                ('keywords', models.TextField(blank=True, verbose_name='کلمات کلیدی')),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('in_scope', models.BooleanField(default=True, verbose_name='در پیشرفت کل')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'module (ماژول تیمیار)',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='teamyar.module'),
        ),
        migrations.AddField(
            model_name='task',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='teamyar.module'),
        ),
        migrations.RunPython(seed_and_file, migrations.RunPython.noop),
    ]
