# Generated by Django 5.1.5 on 2026-09-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='sayad_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sayad_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
