# Generated by Django 5.1.5 on 2026-09-23 07:07

import apps.sales2.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_invoice_channel_backfill'),
        ('sales2', '0002_cheque_sayad_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_margin_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate_pct', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ('min_margin_pct',),
            },
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='grammage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CommissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.CharField(max_length=300)),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_override', to='sales2.salesdocumentline')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('grammage', models.PositiveSmallIntegerField(choices=[(48, '۴۸ گرم'), (55, '۵۵ گرم')])),
                ('is_official', models.BooleanField()),
                ('base_fi_rial', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('waste_pct', models.DecimalField(decimal_places=2, default=Decimal('103'), max_digits=6)),
                ('qty_tiers', models.JSONField(default=apps.sales2.models.default_qty_tiers)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'برگه لیست قیمت',
                'ordering': ('grammage', '-is_official'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('grammage', 'is_official'), name='sales2_one_active_sheet')],
            },
        ),
        migrations.CreateModel(
            name='PriceSheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_mm', models.PositiveSmallIntegerField()),
                ('length_m', models.PositiveSmallIntegerField()),
                ('cut_fee_rial', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('print_fee_rial', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('waste_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('note', models.CharField(blank=True, max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='sales2.pricesheet')),
            ],
            options={
                'ordering': ('sort_order', 'width_mm', 'length_m'),
            },
        ),
        migrations.CreateModel(
            name='AccountingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammage', models.PositiveSmallIntegerField(default=0)),
                ('cost_rial', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales2_costs', to='crm.product')),
            ],
            options={
                'verbose_name': 'فی حسابداری',
                'unique_together': {('product', 'grammage')},
            },
        ),
        migrations.CreateModel(
            name='CommissionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jalali_year', models.PositiveSmallIntegerField()),
                ('jalali_month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'باز'), ('approved', 'تأیید شده')], default='open', max_length=10)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-jalali_year', '-jalali_month'),
                'unique_together': {('jalali_year', 'jalali_month')},
            },
        ),
    ]
