# Generated by Django 5.1.5 on 2026-09-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_invoice_channel_backfill'),
        ('sales2', '0004_seed_commission_tiers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingcost',
            options={'ordering': ('-jalali_year', '-jalali_month'), 'verbose_name': 'فی حسابداری'},
        ),
        migrations.AlterUniqueTogether(
            name='accountingcost',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accountingcost',
            name='jalali_month',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingcost',
            name='jalali_year',
            field=models.PositiveSmallIntegerField(default=1405),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='accountingcost',
            unique_together={('product', 'grammage', 'jalali_year', 'jalali_month')},
        ),
    ]
