# Generated by Django 5.1.5 on 2026-09-23 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def converted_to_issued(apps, schema_editor):
    # «Converted» is now counted from the invoices, not stored.
    apps.get_model("sales2", "SalesDocument").objects.filter(status="converted").update(status="issued")


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0005_accounting_cost_by_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(converted_to_issued, migrations.RunPython.noop),
        migrations.AddField(
            model_name='delivery',
            name='issue_checks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='delivery',
            name='override_reason',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='close_reason',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='return_type',
            field=models.CharField(choices=[('goods', 'مرجوعی کالا'), ('undelivered', 'کسر تحویل\u200cنشده')], default='goods', max_length=12),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادر شده'), ('cancelled', 'ابطال')], default='draft', max_length=10),
        ),
    ]
