# Generated by Django 5.1.5 on 2026-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0007_profiles_monthly_prices_finance_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='opening_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='opening_balance_rial',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='method',
            field=models.CharField(choices=[('cash', 'نقد'), ('transfer', 'واریز / حواله بانکی'), ('pos', 'کارتخوان'), ('cheque', 'چک'), ('arpa', 'تسویه در آرپا')], default='transfer', max_length=10),
        ),
    ]
