# Generated by Django 5.1.5 on 2026-10-01 20:49

import apps.sales2.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0008_cutover_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='grade',
            field=models.CharField(blank=True, choices=[('SP', 'SP · استراتژیک'), ('A', 'A · ممتاز'), ('B', 'B · خوب'), ('C', 'C · پرریسک/کم\u200cاولویت')], max_length=2),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='grade_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='grade_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='grade_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='grade_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='strategic_score',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='sales2setting',
            name='big_order_factor',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=4),
        ),
        migrations.AddField(
            model_name='sales2setting',
            name='grade_weights',
            field=models.JSONField(default=apps.sales2.models.default_grade_weights),
        ),
        migrations.AddField(
            model_name='sales2setting',
            name='margin_floor_pct',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
