# Generated by Django 5.1.5 on 2026-10-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_invoice_channel_backfill'),
        ('sales2', '0009_customer_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingcost',
            options={'ordering': ('-jalali_year', '-jalali_month', '-jalali_day'), 'verbose_name': 'فی حسابداری'},
        ),
        migrations.AlterModelOptions(
            name='pricelistitem',
            options={'ordering': ('-jalali_year', '-jalali_month', '-jalali_day'), 'verbose_name': 'قیمت ثابت لیست'},
        ),
        migrations.AlterModelOptions(
            name='pricesheet',
            options={'ordering': ('-jalali_year', '-jalali_month', '-jalali_day', 'grammage', '-is_official'), 'verbose_name': 'برگه لیست قیمت'},
        ),
        migrations.AlterUniqueTogether(
            name='accountingcost',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pricesheet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accountingcost',
            name='jalali_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='jalali_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pricesheet',
            name='jalali_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='accountingcost',
            unique_together={('product', 'grammage', 'jalali_year', 'jalali_month', 'jalali_day')},
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('product', 'is_official', 'jalali_year', 'jalali_month', 'jalali_day')},
        ),
        migrations.AlterUniqueTogether(
            name='pricesheet',
            unique_together={('grammage', 'is_official', 'jalali_year', 'jalali_month', 'jalali_day')},
        ),
    ]
