# Generated by Django 5.1.5 on 2026-07-26 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_sitesetting'),
        ('sales', '0008_factsalesmonthly_proforma_cancelled_rial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name': 'گروه مشتری',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'شیوه آشنایی',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=120)),
                ('is_controllable', models.BooleanField(default=True, help_text='آیا این دلیل در کنترل ماست؟ (قیمت/تاخیر بله، نیاز مشتری خیر)')),
            ],
            options={
                'verbose_name': 'دلیل شکست',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(choices=[('open', 'در جریان'), ('won', 'موفق'), ('lost', 'ناموفق')], default='open', max_length=8)),
                ('probability_pct', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'مرحله کاریز',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=150)),
                ('unit', models.CharField(choices=[('roll', 'رول'), ('pack', 'بسته'), ('ton', 'تن'), ('sheet', 'برگ')], default='roll', max_length=10)),
                ('list_price_rial', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('unit_cost_rial', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'دسته محصول',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_fa', models.CharField(max_length=60, unique=True)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('company', 'شرکت / سازمان'), ('person', 'شخص حقیقی')], default='company', max_length=10)),
                ('status', models.CharField(choices=[('lead', 'سرنخ'), ('active', 'مشتری فعال'), ('dormant', 'راکد'), ('lost', 'از دست رفته')], default='lead', max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('mobile', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('first_contact_at', models.DateTimeField()),
                ('first_deal_won_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B')], default='team', max_length=16)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='sales.dimemployee')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_customers', to='sales.dimprovince')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='crm.customergroup')),
                ('lead_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='crm.leadsource')),
                ('tags', models.ManyToManyField(blank=True, related_name='customers', to='crm.tag')),
            ],
            options={
                'verbose_name': 'مشتری',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(default=5)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='crm.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='sales.dimemployee')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_feedback', to='core.dimperiod')),
            ],
            options={
                'verbose_name': 'بازخورد مشتری',
                'ordering': ('-at',),
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('open', 'جاری'), ('won', 'موفق'), ('lost', 'ناموفق')], default='open', max_length=8)),
                ('channel', models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B')], default='team', max_length=16)),
                ('lost_note', models.CharField(blank=True, max_length=400)),
                ('amount_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('cost_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('profit_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('discount_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('shipping_cost_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('other_cost_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('opened_at', models.DateTimeField()),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_deals_closed', to='core.dimperiod')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='sales.dimemployee')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_deals_opened', to='core.dimperiod')),
                ('lead_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.leadsource')),
                ('lost_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.lostreason')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.pipelinestage')),
                ('tags', models.ManyToManyField(blank=True, related_name='deals', to='crm.tag')),
            ],
            options={
                'verbose_name': 'معامله',
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='DealStageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('at', models.DateTimeField()),
                ('days_in_previous', models.PositiveIntegerField(default=0)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='crm.deal')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.pipelinestage')),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.pipelinestage')),
            ],
            options={
                'ordering': ('deal', 'at'),
            },
        ),
        migrations.CreateModel(
            name='DealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('unit_price_rial', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('unit_cost_rial', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.deal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_items', to='crm.product')),
            ],
            options={
                'verbose_name': 'ردیف معامله',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='crm.productcategory'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('kind', models.CharField(choices=[('call_out', 'تماس پیگیری'), ('call_in', 'تماس ورودی'), ('quote', 'اعلام قیمت'), ('sample', 'ارسال نمونه'), ('meeting', 'جلسه حضوری'), ('message', 'ارسال پیام'), ('order', 'ثبت سفارش'), ('invoice', 'صدور فاکتور'), ('payment', 'پرداخت')], default='call_out', max_length=12)),
                ('due_at', models.DateTimeField()),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.customer')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.deal')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='sales.dimemployee')),
            ],
            options={
                'verbose_name': 'کار',
                'ordering': ('due_at',),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('call_out', 'تماس پیگیری'), ('call_in', 'تماس ورودی'), ('quote', 'اعلام قیمت'), ('sample', 'ارسال نمونه'), ('meeting', 'جلسه حضوری'), ('message', 'ارسال پیام'), ('order', 'ثبت سفارش'), ('invoice', 'صدور فاکتور'), ('payment', 'پرداخت')], max_length=12)),
                ('at', models.DateTimeField()),
                ('duration_min', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('success', 'موفق'), ('no_answer', 'بی\u200cپاسخ'), ('follow_up', 'نیاز به پیگیری'), ('failed', 'ناموفق')], default='success', max_length=12)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='sales.dimemployee')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to='core.dimperiod')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.customer')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal')),
            ],
            options={
                'verbose_name': 'فعالیت',
                'ordering': ('-at',),
                'indexes': [models.Index(fields=['owner', 'at'], name='crm_activit_owner_i_bf43ed_idx'), models.Index(fields=['kind', 'result'], name='crm_activit_kind_1b0e3f_idx'), models.Index(fields=['period'], name='crm_activit_period__cd06a7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status', 'closed_at'], name='crm_deal_status_8ccc11_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['owner', 'status'], name='crm_deal_owner_i_e6ee3e_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['opened_at'], name='crm_deal_opened__4320c2_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['close_period', 'status'], name='crm_deal_close_p_bfc421_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['owner', 'first_deal_won_at'], name='crm_custome_owner_i_492c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['province'], name='crm_custome_provinc_142003_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='crm_custome_status_d337ab_idx'),
        ),
    ]
