# Generated by Django 5.1.5 on 2026-07-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadsource',
            options={'ordering': ('name_fa',), 'verbose_name': 'منبع سرنخ'},
        ),
        migrations.AlterModelOptions(
            name='lostreason',
            options={'ordering': ('name_fa',), 'verbose_name': 'دلیل از دست رفتن'},
        ),
        migrations.AlterModelOptions(
            name='pipelinestage',
            options={'ordering': ('order', 'id'), 'verbose_name': 'مرحله فروش'},
        ),
    ]
