# Generated by Django 5.1.5 on 2026-07-26 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesetting_min_week_days_sitesetting_sales_grain'),
        ('crm', '0002_alter_leadsource_options_alter_lostreason_options_and_more'),
        ('sales', '0011_merge_20260727_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoProvinceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B')], default='team', max_length=16)),
                ('target_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_demo_targets', to='core.dimperiod')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_demo_targets', to='sales.dimprovince')),
            ],
            options={
                'verbose_name': 'تارگت استانی (دمو)',
                'unique_together': {('period', 'province', 'channel')},
            },
        ),
    ]
