# Generated by Django 5.1.5 on 2026-08-15 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesetting_sales_grain'),
        ('crm', '0004_dataset_tag'),
        ('sales', '0014_seed_customer_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='economic_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_good_payer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_intercompany',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_cert_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.CharField(choices=[('real', 'داده واقعی'), ('demo', 'داده نمایشی')], db_index=True, default='real', max_length=4)),
                ('code', models.SlugField(unique=True)),
                ('number', models.CharField(max_length=30)),
                ('kind', models.CharField(choices=[('sale', 'فاکتور فروش'), ('return', 'مرجوع از فروش')], default='sale', max_length=8)),
                ('issued_at', models.DateField()),
                ('amount_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('discount_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('vat_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('settled_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('unsettled_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('payment_terms', models.CharField(blank=True, max_length=40)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('grace_date', models.DateField(blank=True, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=60)),
                ('created_by_name', models.CharField(blank=True, max_length=60)),
                ('channel', models.CharField(blank=True, choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B')], max_length=16)),
                ('branch', models.CharField(blank=True, max_length=60)),
                ('tax_ref', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.customer')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.deal')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.dimemployee')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_invoices', to='core.dimperiod')),
            ],
            options={
                'verbose_name': 'فاکتور فروش',
                'ordering': ('-issued_at', '-number'),
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.CharField(choices=[('real', 'داده واقعی'), ('demo', 'داده نمایشی')], db_index=True, default='real', max_length=4)),
                ('product_code', models.CharField(blank=True, max_length=40)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('equivalent', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sub_unit', models.CharField(blank=True, max_length=20)),
                ('unit_price_rial', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('amount_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('accounting_group', models.CharField(blank=True, max_length=40)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.salesinvoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='crm.product')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerExternalRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.CharField(choices=[('real', 'داده واقعی'), ('demo', 'داده نمایشی')], db_index=True, default='real', max_length=4)),
                ('source', models.CharField(choices=[('didar', 'دیدار'), ('arpa', 'آرپا (حسابداری)')], max_length=8)),
                ('external_id', models.CharField(max_length=64)),
                ('external_name', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_refs', to='crm.customer')),
            ],
            options={
                'verbose_name': 'شناسه در سامانه مبدأ',
                'indexes': [models.Index(fields=['customer', 'source'], name='crm_custome_custome_37cf56_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='crm_extref_unique_source_id')],
            },
        ),
        migrations.CreateModel(
            name='CustomerMatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('didar', 'دیدار'), ('arpa', 'آرپا (حسابداری)')], max_length=8)),
                ('external_id', models.CharField(max_length=64)),
                ('external_name', models.CharField(max_length=200)),
                ('external_phone', models.CharField(blank=True, max_length=40)),
                ('external_city', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('method', models.CharField(choices=[('nid', 'شناسه/کد ملی'), ('phone', 'تلفن'), ('name', 'نام یکسان'), ('fuzzy', 'نام مشابه'), ('manual', 'دستی')], max_length=8)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('state', models.CharField(choices=[('pending', 'در انتظار بازبینی'), ('accepted', 'تایید شد — همان مشتری'), ('rejected', 'رد شد — مشتری دیگری است')], db_index=True, default='pending', max_length=8)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='crm.customer')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_match_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیشنهاد تطبیق مشتری',
                'ordering': ('state', '-score'),
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id', 'customer'), name='crm_matchcand_unique_pair')],
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['customer', 'issued_at'], name='crm_salesin_custome_df8389_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['period', 'kind'], name='crm_salesin_period__2dd93d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['owner', 'issued_at'], name='crm_salesin_owner_i_757461_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceitem',
            index=models.Index(fields=['invoice'], name='crm_salesin_invoice_1422ae_idx'),
        ),
    ]
