# Generated by Django 5.1.5 on 2026-08-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_backfill_didar_external_refs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermatchcandidate',
            name='method',
            field=models.CharField(choices=[('nid', 'شناسه/کد ملی'), ('phone', 'تلفن'), ('name', 'نام یکسان'), ('ambig', 'نام یکسان با چند مشتری'), ('fuzzy', 'نام مشابه'), ('manual', 'دستی')], max_length=8),
        ),
    ]
