# Generated by Django 5.1.5 on 2026-08-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_customermatchcandidate_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermatchcandidate',
            name='method',
            field=models.CharField(choices=[('nid', 'شناسه/کد ملی'), ('branch', 'شناسه ملی یکسان، شعبه\u200cی متفاوت'), ('phone', 'تلفن'), ('name', 'نام یکسان'), ('ambig', 'نام یکسان با چند مشتری'), ('fuzzy', 'نام مشابه'), ('manual', 'دستی')], max_length=8),
        ),
    ]
