# Generated by Django 5.1.5 on 2026-08-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_customermatchcandidate_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermatchcandidate',
            name='duplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='customerexternalref',
            name='source',
            field=models.CharField(choices=[('didar', 'دیدار'), ('arpa', 'آرپا (حسابداری)'), ('crm', 'داخل CRM')], max_length=8),
        ),
        migrations.AlterField(
            model_name='customermatchcandidate',
            name='source',
            field=models.CharField(choices=[('didar', 'دیدار'), ('arpa', 'آرپا (حسابداری)'), ('crm', 'داخل CRM')], max_length=8),
        ),
    ]
