# Generated by Django 5.1.5 on 2026-09-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_customermatchcandidate_duplicate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='channel',
            field=models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B'), ('psp', 'فروش PSP')], default='team', max_length=16),
        ),
        migrations.AlterField(
            model_name='deal',
            name='channel',
            field=models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B'), ('psp', 'فروش PSP')], default='team', max_length=16),
        ),
        migrations.AlterField(
            model_name='demoprovincetarget',
            name='channel',
            field=models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B'), ('psp', 'فروش PSP')], default='team', max_length=16),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='channel',
            field=models.CharField(blank=True, choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B'), ('psp', 'فروش PSP')], max_length=16),
        ),
    ]
