# Generated by Django 5.1.5 on 2026-09-17 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_customer_channel_alter_deal_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('didar', 'دیدار'), ('arpa', 'آرپا (حسابداری)'), ('crm', 'داخل CRM')], max_length=8)),
                ('external_id', models.CharField(max_length=64)),
                ('external_name', models.CharField(blank=True, max_length=200)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_dismissed_parties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طرف\u200cحساب حذف\u200cشده',
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='crm_dismissed_unique')],
            },
        ),
    ]
