# Generated by Django 5.1.5 on 2026-09-17 11:40

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    # Existing invoices were only ever written for matched parties, so their
    # آرپا code is recoverable from the customer's ref, and whether they are
    # intercompany from the customer's flag. Without this the first report
    # after migrating would count sister-company billing as sales.
    Invoice = apps.get_model("crm", "SalesInvoice")
    Ref = apps.get_model("crm", "CustomerExternalRef")
    codes = {}
    for customer_id, external_id, name in Ref.objects.filter(
        source="arpa"
    ).values_list("customer_id", "external_id", "external_name"):
        codes.setdefault(customer_id, (external_id, name))
    for inv in Invoice.objects.select_related("customer").only(
        "pk", "customer_id", "customer__is_intercompany", "customer__name_fa"
    ):
        code, name = codes.get(inv.customer_id, ("", ""))
        Invoice.objects.filter(pk=inv.pk).update(
            party_code=code[:64],
            party_name=(name or (inv.customer.name_fa if inv.customer else ""))[:200],
            is_intercompany=bool(inv.customer and inv.customer.is_intercompany),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_dismissed_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='is_intercompany',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='party_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='party_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.customer'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
