# Generated by Django 5.1.5 on 2026-08-06 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('overview', 'نمای کلی سازمان'), ('sales_team', 'فروش همکار'), ('sales_org', 'فروش بانکی'), ('sales_b2b', 'فروش B2B'), ('production', 'تولید'), ('finance', 'مالی'), ('commercial', 'بازرگانی'), ('crm', 'CRM')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('is_default', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'داشبورد',
                'verbose_name_plural': 'داشبوردها',
                'ordering': ('section', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('kpi', 'کارت شاخص'), ('progress', 'نوار پیشرفت (واقعی/هدف)'), ('gauge', 'گیج'), ('bar', 'ستونی'), ('hbar', 'میله\u200cای افقی'), ('line', 'خطی'), ('area', 'سطحی'), ('stacked', 'ستونی انباشته'), ('pie', 'دایره\u200cای'), ('donut', 'دونات'), ('table', 'جدول'), ('text', 'متن / یادداشت'), ('divider', 'عنوان بخش')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('x', models.PositiveSmallIntegerField(default=0)),
                ('y', models.PositiveSmallIntegerField(default=0)),
                ('w', models.PositiveSmallIntegerField(default=4)),
                ('h', models.PositiveSmallIntegerField(default=4)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.dashboard')),
            ],
            options={
                'verbose_name': 'ویجت',
                'verbose_name_plural': 'ویجت\u200cها',
                'ordering': ('dashboard', 'y', 'x', 'sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['section', 'is_default'], name='dashboards__section_73f80a_idx'),
        ),
    ]
