# Generated by Django 5.1.5 on 2026-08-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='section',
            field=models.CharField(choices=[('overview', 'نمای کلی سازمان'), ('sales_team', 'فروش همکار'), ('sales_org', 'فروش بانکی'), ('sales_b2b', 'فروش B2B'), ('production', 'تولید'), ('finance', 'مالی'), ('commercial', 'بازرگانی داخلی'), ('commercial_foreign', 'بازرگانی خارجی'), ('crm', 'CRM')], db_index=True, max_length=20),
        ),
    ]
