# Generated by Django 5.1.5 on 2026-07-17 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('bank', 'Bank'), ('psp', 'Payment service provider')], default='bank', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('full_name_fa', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='sales.dimteam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.dimbank')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='core.dimperiod')),
            ],
            options={
                'unique_together': {('period', 'bank')},
            },
        ),
        migrations.CreateModel(
            name='FactKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('company', 'Company'), ('team', 'Team'), ('employee', 'Employee')], max_length=10)),
                ('scope_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scope_label', models.CharField(blank=True, max_length=150)),
                ('actual', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('target', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('ideal', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('deviation', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('efficiency_pct', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dimkpi')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='core.dimperiod')),
            ],
            options={
                'ordering': ('period', 'kpi', 'scope'),
                'unique_together': {('period', 'kpi', 'scope', 'scope_id')},
            },
        ),
        migrations.CreateModel(
            name='FactSalesMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenue_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('active_customers', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('profit_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('cost_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('target_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.dimemployee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.dimperiod')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period__jalali_year', '-period__jalali_month', 'employee'),
                'unique_together': {('period', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='FactSalesProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('target_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_sales', to='core.dimperiod')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.dimprovince')),
            ],
            options={
                'unique_together': {('period', 'province')},
            },
        ),
    ]
