# Generated by Django 5.1.5 on 2026-07-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactKPI',
        ),
    ]
