# Generated by Django 5.1.5 on 2026-07-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_factkpi_unique_together_factkpi_channel_and_more'),
        ('sales', '0003_alter_factsalesmonthly_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factsalesprovince',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='factsalesprovince',
            name='channel',
            field=models.CharField(choices=[('team', 'تیم فروش (همکار)'), ('organizational', 'فروش سازمانی')], default='team', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='factsalesprovince',
            unique_together={('period', 'province', 'channel')},
        ),
    ]
