# Generated by Django 5.1.5 on 2026-07-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_factsalesmonthly_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factsalesmonthly',
            name='channel',
            field=models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B')], default='team', max_length=16),
        ),
        migrations.AlterField(
            model_name='factsalesprovince',
            name='channel',
            field=models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B')], default='team', max_length=16),
        ),
    ]
