# Generated by Django 5.1.5 on 2026-07-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_factsalesmonthly_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsalesmonthly',
            name='collected_rial',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ وصول\u200cشده از فروش این ماه (فقط B2B)', max_digits=20),
        ),
        migrations.AddField(
            model_name='factsalesmonthly',
            name='quantity_ton',
            field=models.DecimalField(decimal_places=3, default=0, help_text='مقدار فروش به تن (فقط B2B)', max_digits=14),
        ),
        migrations.AddField(
            model_name='factsalesmonthly',
            name='receivables_rial',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مانده مطالبات وصول\u200cنشده (فقط B2B)', max_digits=20),
        ),
    ]
