# Generated by Django 5.1.5 on 2026-07-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_factsalesmonthly_collected_rial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsalesmonthly',
            name='proforma_cancelled_rial',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ پیش\u200cفاکتورهای کنسل\u200cشده (فقط فروش همکار)', max_digits=20),
        ),
        migrations.AddField(
            model_name='factsalesmonthly',
            name='proforma_issued_rial',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ پیش\u200cفاکتورهای صادره (فقط فروش همکار)', max_digits=20),
        ),
        migrations.AddField(
            model_name='factsalesmonthly',
            name='won_invoices_rial',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ فاکتورهای برنده\u200cشده در مناقصه (فقط B2B)', max_digits=20),
        ),
    ]
