# Generated by Django 5.1.5 on 2026-07-25 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesetting_min_week_days_sitesetting_sales_grain'),
        ('sales', '0008_factsalesmonthly_proforma_cancelled_rial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B')], default='team', max_length=16)),
                ('target_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='sales.dimemployee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='core.dimperiod')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='sales.dimprovince')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('province', None)), fields=('period', 'channel', 'employee'), name='uniq_employee_target'), models.UniqueConstraint(condition=models.Q(('employee', None)), fields=('period', 'channel', 'province'), name='uniq_province_target')],
            },
        ),
    ]
