# Generated by Django 5.1.5 on 2026-07-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_dimemployee_user'),
        ('sales', '0010_move_targets_to_salestarget'),
    ]

    operations = [
    ]
