# Generated by Django 5.1.5 on 2026-07-30 19:49

import django.db.models.deletion
from django.db import migrations, models


def backfill_roster(apps, schema_editor):
    """
    Seed each channel's roster from the figures already recorded.

    Without this every department would open the new page to an empty list and
    have to retype people the system can already see — anyone who has ever had
    a fact row in a channel plainly works in it.
    """
    Fact = apps.get_model("sales", "FactSalesMonthly")
    Membership = apps.get_model("sales", "EmployeeChannel")
    pairs = set(Fact.objects.values_list("employee_id", "channel"))
    Membership.objects.bulk_create(
        [Membership(employee_id=e, channel=c, is_active=True) for e, c in pairs],
        ignore_conflicts=True,
    )


def drop_roster(apps, schema_editor):
    apps.get_model("sales", "EmployeeChannel").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_merge_20260727_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B')], max_length=16)),
                ('is_active', models.BooleanField(default=True, help_text='کارشناسی که دیگر در این بخش کار نمی\u200cکند غیرفعال می\u200cشود، نه حذف — تا سابقه فروشش در گزارش\u200cهای قبلی باقی بماند.')),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='sales.dimemployee')),
            ],
            options={
                'verbose_name': 'عضویت کارشناس در بخش',
                'ordering': ('-is_active', 'employee__full_name_fa'),
                'unique_together': {('employee', 'channel')},
            },
        ),
            migrations.RunPython(backfill_roster, drop_roster),
    ]
