# Generated by Django 5.1.5 on 2026-08-02 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesetting_sales_grain'),
        ('sales', '0012_employeechannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimCustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_fa', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'customer group (گروه مشتری)',
                'ordering': ('sort_order', 'name_fa'),
            },
        ),
        migrations.CreateModel(
            name='FactSalesByCustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B')], default='b2b', max_length=16)),
                ('sales_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('profit_rial', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('customer_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.dimcustomergroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_group_sales', to='core.dimperiod')),
            ],
            options={
                'ordering': ('period', 'customer_group__sort_order'),
                'unique_together': {('period', 'customer_group', 'channel')},
            },
        ),
    ]
