# Generated by Django 5.1.5 on 2026-09-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_seed_customer_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeechannel',
            name='channel',
            field=models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B'), ('psp', 'فروش PSP')], max_length=16),
        ),
        migrations.AlterField(
            model_name='factsalesbycustomergroup',
            name='channel',
            field=models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B'), ('psp', 'فروش PSP')], default='b2b', max_length=16),
        ),
        migrations.AlterField(
            model_name='factsalesmonthly',
            name='channel',
            field=models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B'), ('psp', 'فروش PSP')], default='team', max_length=16),
        ),
        migrations.AlterField(
            model_name='factsalesprovince',
            name='channel',
            field=models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B'), ('psp', 'فروش PSP')], default='team', max_length=16),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='channel',
            field=models.CharField(choices=[('team', 'فروش همکار'), ('organizational', 'فروش بانکی'), ('b2b', 'فروش B2B'), ('psp', 'فروش PSP')], default='team', max_length=16),
        ),
    ]
