# Generated by Django 5.1.5 on 2026-09-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_sheet_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimemployee',
            name='archive_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dimemployee',
            name='archived_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimemployee',
            name='hired_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimemployee',
            name='mobile',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='dimemployee',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
