<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import api from "@/api/client";
import { useMoney, loadMoneySettings } from "@/composables/useMoney";
import { apiError } from "@/components/crm/formError";
import Skeleton from "@/components/Skeleton.vue";

/**
 * تحلیل هوشمند — a written reading of the month, and a box to ask questions.
 *
 * Nothing here is generated by a language model: the server compares the
 * month with the one before, its own trend and its plan (see
 * backend/apps/dashboards/insights.py and ask.py). The text arrives with
 * placeholders and the numbers beside it, so money is shown in the viewer's
 * own unit (ریال / تومان) exactly like every other page.
 */
interface Num { v: number | null; unit: string }
interface Finding { tone: "good" | "bad" | "warn" | "info"; text: string; values: Record<string, Num> }
interface Section {
  key: string; label: string;
  stats: { label: string; value: Num; change?: Num }[];
  findings: Finding[];
}
interface Answer {
  ok: boolean; understood?: string; answer: string; values: Record<string, Num>;
  table?: { columns: string[]; rows: (string | Num)[][] };
  suggestions?: string[];
  /** Sent back with the next question, so «ماه قبلش؟» is read against this one. */
  context?: Record<string, unknown>;
}

const { money, unitLabel } = useMoney();
const FA = new Intl.NumberFormat("fa-IR", { maximumFractionDigits: 1 });

const periods = ref<{ id: number; label: string }[]>([]);
const period = ref<number | null>(null);
const periodLabel = ref("");
const comparedTo = ref<string | null>(null);
const sections = ref<Section[]>([]);
const summary = ref<Finding[]>([]);
const loading = ref(true);
const error = ref("");

const question = ref("");
const asking = ref(false);
const thread = ref<{ q: string; a: Answer }[]>([]);
/** The last answered question's context — null starts a fresh conversation. */
const conversation = ref<Record<string, unknown> | null>(null);

/** Sent by the server, from the sections this viewer may read. */
const examples = ref<string[]>([]);

function fmt(n: Num | null | undefined): string {
  if (!n || n.v === null || n.v === undefined) return "—";
  switch (n.unit) {
    case "rial": return money(n.v);
    case "percent": return `${FA.format(n.v)}٪`;
    case "pp": return FA.format(n.v);
    case "ton": return `${FA.format(n.v)} تن`;
    default: return FA.format(n.v);
  }
}

/** Splits a finding into text and number pieces, so the numbers can be styled. */
function pieces(text: string, values: Record<string, Num>) {
  const out: { t: string; num?: boolean }[] = [];
  const re = /\{(\w+)\}/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) {
    if (m.index > last) out.push({ t: text.slice(last, m.index) });
    out.push({ t: fmt(values[m[1]]), num: true });
    last = m.index + m[0].length;
  }
  if (last < text.length) out.push({ t: text.slice(last) });
  return out;
}

const TONE: Record<string, { dot: string; ring: string; label: string }> = {
  bad: { dot: "bg-red-500", ring: "border-red-100 bg-red-50/60", label: "نیاز به توجه" },
  warn: { dot: "bg-amber-500", ring: "border-amber-100 bg-amber-50/60", label: "هشدار" },
  good: { dot: "bg-emerald-500", ring: "border-emerald-100 bg-emerald-50/60", label: "خوب" },
  info: { dot: "bg-slate-300", ring: "border-slate-100 bg-surface", label: "" },
};

async function load() {
  loading.value = true;
  error.value = "";
  try {
    const { data } = await api.get("/dashboards/insights/", {
      params: period.value ? { period: period.value } : {},
    });
    periods.value = data.periods ?? [];
    sections.value = data.sections ?? [];
    summary.value = data.summary ?? [];
    comparedTo.value = data.compared_to;
    examples.value = data.examples ?? [];
    periodLabel.value = data.period?.label ?? "";
    if (data.period && period.value !== data.period.id) period.value = data.period.id;
  } catch (e) {
    error.value = apiError(e);
  } finally {
    loading.value = false;
  }
}

async function ask(text?: string) {
  const q = (text ?? question.value).trim();
  if (!q || asking.value) return;
  asking.value = true;
  try {
    const { data } = await api.post("/dashboards/ask/", {
      question: q, period: period.value, context: conversation.value,
    });
    thread.value.unshift({ q, a: data });
    if (data.context) conversation.value = data.context;
    question.value = "";
  } catch (e) {
    thread.value.unshift({ q, a: { ok: false, answer: apiError(e), values: {} } });
  } finally {
    asking.value = false;
  }
}

const chips = computed(() => {
  const last = thread.value[0]?.a.suggestions;
  return last?.length ? last : examples.value;
});

const periodsNewestFirst = computed(() => [...periods.value].reverse());

onMounted(async () => {
  await loadMoneySettings();
  await load();
});
watch(period, (now, before) => {
  if (before !== null && now !== before) {
    // Another month on the picker is another conversation.
    conversation.value = null;
    load();
  }
});

function restart() {
  conversation.value = null;
  thread.value = [];
}
</script>

<template>
  <div class="space-y-4 max-w-5xl">
    <div class="flex flex-wrap items-center justify-between gap-2">
      <div>
        <h1 class="text-xl font-bold text-ink">تحلیل هوشمند</h1>
        <p class="text-xs text-slate-400 mt-0.5">
          خوانش خودکار عددهای ثبت‌شده{{ comparedTo ? ` — مقایسه با ${comparedTo}` : "" }} · مبالغ به {{ unitLabel }}
        </p>
      </div>
      <select
        v-model.number="period"
        class="border border-slate-200 rounded-xl px-3 py-1.5 bg-surface text-sm focus:outline-none focus:ring-2 focus:ring-brand-500/30 transition"
        aria-label="ماه"
      >
        <option v-for="p in periodsNewestFirst" :key="p.id" :value="p.id">{{ p.label }}</option>
      </select>
    </div>

    <!-- پرسش -->
    <div class="bg-surface rounded-card shadow-soft p-4 space-y-3">
      <form class="flex gap-2" @submit.prevent="ask()">
        <input
          v-model="question"
          type="text"
          maxlength="300"
          :placeholder="conversation
            ? 'ادامه بدهید… مثلاً «ماه قبلش؟»، «اصفهان چطور؟» یا «به تفکیک کارشناس»'
            : `بپرسید… مثلاً «فروش تهران در ${periodLabel || 'این ماه'}»`"
          class="flex-1 min-w-0 border border-slate-200 rounded-xl px-3 py-2 text-sm bg-surface focus:outline-none focus:ring-2 focus:ring-brand-500/30"
        />
        <button
          type="submit"
          :disabled="asking || !question.trim()"
          class="shrink-0 rounded-xl bg-brand-600 text-white text-sm px-4 py-2 disabled:opacity-50"
        >
          {{ asking ? "…" : "بپرس" }}
        </button>
      </form>
      <p v-if="conversation" class="flex items-center justify-between text-[11px] text-slate-400">
        <span>سؤال بعدی در ادامه‌ی همین گفتگو خوانده می‌شود.</span>
        <button class="text-brand-600 hover:underline" @click="restart">گفتگوی تازه</button>
      </p>
      <!-- Always right under the box: the last answer's follow-ups, or the
           starting questions before anything has been asked. -->
      <div v-if="chips.length" class="flex flex-wrap gap-1.5">
        <button
          v-for="ex in chips" :key="ex"
          class="text-xs rounded-full border border-slate-200 px-2.5 py-1 text-slate-500 hover:bg-slate-50"
          @click="ask(ex)"
        >{{ ex }}</button>
      </div>

      <div v-for="(item, i) in thread" :key="i" class="border-t border-slate-100 pt-3 space-y-2">
        <p class="text-sm font-medium text-ink">{{ item.q }}</p>
        <p v-if="item.a.understood" class="text-[11px] text-slate-400">برداشت: {{ item.a.understood }}</p>
        <p class="text-sm leading-7" :class="item.a.ok ? 'text-slate-700' : 'text-amber-700'">
          <template v-for="(pc, j) in pieces(item.a.answer, item.a.values)" :key="j">
            <b v-if="pc.num" class="font-semibold text-ink">{{ pc.t }}</b>
            <template v-else>{{ pc.t }}</template>
          </template>
        </p>
        <div v-if="item.a.table?.rows.length" class="overflow-x-auto">
          <table class="w-full text-xs">
            <thead>
              <tr class="text-slate-400">
                <th v-for="c in item.a.table.columns" :key="c" class="text-right font-normal py-1 px-2">{{ c }}</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(row, r) in item.a.table.rows" :key="r" class="border-t border-slate-100">
                <td v-for="(cell, c) in row" :key="c" class="py-1.5 px-2" :class="c ? 'text-left whitespace-nowrap' : 'text-ink'">
                  {{ typeof cell === "string" ? cell : fmt(cell) }}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div v-if="loading" class="space-y-3">
      <Skeleton class="h-40 rounded-card" />
      <Skeleton class="h-64 rounded-card" />
    </div>
    <p v-else-if="error" class="bg-red-50 text-red-600 text-sm rounded-xl px-3 py-2">{{ error }}</p>

    <template v-else>
      <!-- مهم‌ترین نکته‌ها -->
      <div v-if="summary.length" class="bg-surface rounded-card shadow-soft p-4">
        <p class="text-sm text-slate-500 mb-3">مهم‌ترین نکته‌های {{ periodLabel }}</p>
        <ul class="space-y-2">
          <li v-for="(f, i) in summary" :key="i" class="flex gap-2 text-sm leading-7">
            <span class="mt-2.5 h-2 w-2 shrink-0 rounded-full" :class="TONE[f.tone].dot" />
            <span>
              <template v-for="(pc, j) in pieces(f.text, f.values)" :key="j">
                <b v-if="pc.num" class="font-semibold text-ink">{{ pc.t }}</b>
                <template v-else>{{ pc.t }}</template>
              </template>
            </span>
          </li>
        </ul>
      </div>

      <p v-if="!sections.length" class="text-sm text-slate-500 bg-surface rounded-card shadow-soft p-4">
        برای بخش‌هایی که به آن‌ها دسترسی دارید، داده‌ای برای تحلیل پیدا نشد.
      </p>

      <!-- هر بخش -->
      <div v-for="s in sections" :key="s.key" class="bg-surface rounded-card shadow-soft p-4 space-y-3">
        <div class="flex flex-wrap items-baseline justify-between gap-2">
          <h2 class="font-bold text-ink">{{ s.label }}</h2>
          <div class="flex flex-wrap gap-4">
            <div v-for="st in s.stats" :key="st.label" class="text-left">
              <p class="text-[11px] text-slate-400">{{ st.label }}</p>
              <p class="text-sm font-bold text-ink">
                {{ fmt(st.value) }}
                <span
                  v-if="st.change && st.change.v !== null"
                  class="text-[11px] font-normal"
                  :class="st.change.v >= 0 ? 'text-emerald-600' : 'text-red-600'"
                >{{ st.change.v >= 0 ? "▲" : "▼" }} {{ FA.format(Math.abs(st.change.v)) }}٪</span>
              </p>
            </div>
          </div>
        </div>
        <ul class="space-y-1.5">
          <li
            v-for="(f, i) in s.findings" :key="i"
            class="flex gap-2 text-sm leading-7 rounded-xl border px-3 py-1.5"
            :class="TONE[f.tone].ring"
          >
            <span class="mt-2.5 h-2 w-2 shrink-0 rounded-full" :class="TONE[f.tone].dot" />
            <span>
              <template v-for="(pc, j) in pieces(f.text, f.values)" :key="j">
                <b v-if="pc.num" class="font-semibold text-ink">{{ pc.t }}</b>
                <template v-else>{{ pc.t }}</template>
              </template>
            </span>
          </li>
        </ul>
      </div>

      <p class="text-[11px] text-slate-400 px-1">
        این تحلیل با قاعده‌های ثابت از روی همان عددهای داشبوردها محاسبه می‌شود و فقط ردیف‌های تاییدشده را می‌خواند.
        هیچ داده‌ای به سرویس بیرونی فرستاده نمی‌شود.
      </p>
    </template>
  </div>
</template>
